/*
 * Copyright 2016-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 * 
 * http://aws.amazon.com/apache2.0
 * 
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */
package com.amazonaws.services.customerprofiles.model;

import java.io.Serializable;
import javax.annotation.Generated;

/**
 * 
 * @see <a href="http://docs.aws.amazon.com/goto/WebAPI/customer-profiles-2020-08-15/PutProfileObject" target="_top">AWS
 *      API Documentation</a>
 */
@Generated("com.amazonaws:aws-java-sdk-code-generator")
public class PutProfileObjectResult extends com.amazonaws.AmazonWebServiceResult<com.amazonaws.ResponseMetadata> implements Serializable, Cloneable {

    /**
     * <p>
     * The unique identifier of the profile object generated by the service.
     * </p>
     */
    private String profileObjectUniqueKey;

    /**
     * <p>
     * The unique identifier of the profile object generated by the service.
     * </p>
     * 
     * @param profileObjectUniqueKey
     *        The unique identifier of the profile object generated by the service.
     */

    public void setProfileObjectUniqueKey(String profileObjectUniqueKey) {
        this.profileObjectUniqueKey = profileObjectUniqueKey;
    }

    /**
     * <p>
     * The unique identifier of the profile object generated by the service.
     * </p>
     * 
     * @return The unique identifier of the profile object generated by the service.
     */

    public String getProfileObjectUniqueKey() {
        return this.profileObjectUniqueKey;
    }

    /**
     * <p>
     * The unique identifier of the profile object generated by the service.
     * </p>
     * 
     * @param profileObjectUniqueKey
     *        The unique identifier of the profile object generated by the service.
     * @return Returns a reference to this object so that method calls can be chained together.
     */

    public PutProfileObjectResult withProfileObjectUniqueKey(String profileObjectUniqueKey) {
        setProfileObjectUniqueKey(profileObjectUniqueKey);
        return this;
    }

    /**
     * Returns a string representation of this object. This is useful for testing and debugging. Sensitive data will be
     * redacted from this string using a placeholder value.
     *
     * @return A string representation of this object.
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getProfileObjectUniqueKey() != null)
            sb.append("ProfileObjectUniqueKey: ").append(getProfileObjectUniqueKey());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof PutProfileObjectResult == false)
            return false;
        PutProfileObjectResult other = (PutProfileObjectResult) obj;
        if (other.getProfileObjectUniqueKey() == null ^ this.getProfileObjectUniqueKey() == null)
            return false;
        if (other.getProfileObjectUniqueKey() != null && other.getProfileObjectUniqueKey().equals(this.getProfileObjectUniqueKey()) == false)
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode + ((getProfileObjectUniqueKey() == null) ? 0 : getProfileObjectUniqueKey().hashCode());
        return hashCode;
    }

    @Override
    public PutProfileObjectResult clone() {
        try {
            return (PutProfileObjectResult) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new IllegalStateException("Got a CloneNotSupportedException from Object.clone() " + "even though we're Cloneable!", e);
        }
    }

}
