version: 0.2

phases:
  install:
    runtime-versions:
      java: "$JAVA_RUNTIME"
    commands:
      - apt-get update
      - pip install awscli --upgrade --user
      - pip install rsa
      - pip install typing

  pre_build:
    commands:
    - ROOT=`pwd`
    - SETTINGS_XML_TEMPLATE=release-resources/buildspecs/resources/release-settings.xml
    - SETTINGS_XML=release-settings-final.xml
    - SDK_SIGNING_GPG_SECRING=secring.gpg
    - SDK_SIGNING_GPG_SECRING_ARN="arn:aws:secretsmanager:us-east-1:103431983078:secret:sdk-signing-gpg-secret-ring-9d0YXc"
    - SDK_SIGNING_GPG_KEYNAME_ARN="arn:aws:secretsmanager:us-east-1:103431983078:secret:sdk-signing-gpg-keyname-wFsOOg"
    - SDK_SIGNING_GPG_PASSPHRASE_ARN="arn:aws:secretsmanager:us-east-1:103431983078:secret:sdk-signing-gpg-passphrase-A0H1Kq"
    - SONATYPE_PASSWORD_ARN="arn:aws:secretsmanager:us-east-1:103431983078:secret:sonatype-password-I2V6Y0"

  build:
    commands:
    - RELEASE_VERSION=`mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec`
    - SONATYPE_URL="https://aws.oss.sonatype.org/service/local/repositories/releases/content/com/amazonaws/aws-java-sdk/$RELEASE_VERSION/"
    - |
      if ! curl -f --head $SONATYPE_URL; then
        SONATYPE_PASSWORD=`aws secretsmanager get-secret-value --secret-id $SONATYPE_PASSWORD_ARN --query SecretString --output text`
        SDK_SIGNING_GPG_KEYNAME=`aws secretsmanager get-secret-value --secret-id $SDK_SIGNING_GPG_KEYNAME_ARN --query SecretString --output text`
        SDK_SIGNING_GPG_PASSPHRASE=`aws secretsmanager get-secret-value --secret-id $SDK_SIGNING_GPG_PASSPHRASE_ARN --query SecretString --output text`
        aws secretsmanager get-secret-value --secret-id  $SDK_SIGNING_GPG_SECRING_ARN --query SecretBinary --output text | base64 -d > $SDK_SIGNING_GPG_SECRING
        gpg --passphrase $SDK_SIGNING_GPG_PASSPHRASE --batch --import $SDK_SIGNING_GPG_SECRING

        cat $SETTINGS_XML_TEMPLATE | \
          awk 'BEGIN { var=ENVIRON["SONATYPE_PASSWORD"] } { gsub("\\$SONATYPE_PASSWORD", var, $0); print }' | \
          awk 'BEGIN { var=ENVIRON["SDK_SIGNING_GPG_PASSPHRASE"] } { gsub("\\$SDK_SIGNING_GPG_PASSPHRASE", var, $0); print }' | \
          awk 'BEGIN { var=ENVIRON["SDK_SIGNING_GPG_KEYNAME"] } { gsub("\\$SDK_SIGNING_GPG_KEYNAME", var, $0); print }' > \
          $SETTINGS_XML

        mvn clean -U deploy -B -s $SETTINGS_XML -Ppublishing -DperformRelease -Dfindbugs.skip -DskipTests -Dcheckstyle.skip -DadditionalJOption=-Xdoclint:none -DadditionalJOption=--allow-script-in-comments -DautoReleaseAfterClose=true -DstagingProgressTimeoutMinutes=30 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true
      else
        echo "This version was already released."
      fi
