[default]
aws_access_key_id=testDefault
aws_secret_access_key=testDefault
[test]
aws_access_key_id=testProfile1
aws_secret_access_key=testProfile1
[test]
aws_access_key_id=testProfile2
aws_secret_access_key=testProfile2
aws_session_token = testProfile2